server.port=8081
###########################################
#
#	freemarker 静态资源配置
#
###########################################

##设定ftl文件路径
spring.freemarker.template-loader-path=classpath:/templates
##关闭缓存，即时刷新，上线生产环境部署需要改为true
spring.freemarker.allow-request-override=false
spring.freemarker.cache=false
spring.freemarker.check-template-location=true
spring.freemarker.charset=UTF-8
spring.freemarker.content-type=text/html
spring.freemarker.expose-request-attributes=false
spring.freemarker.expose-session-attributes=false
spring.freemarker.request-context-attribute=request
spring.freemarker.suffix=.ftl
spring.freemarker.expose-spring-macro-helpers=false

####################################################
#
#	数据源配置
#
####################################################
spring.datasource.url=jdbc:mysql://localhost:3306/user
spring.datasource.username=root
spring.datasource.password=rootroot
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.druid.initial-size=1
spring.datasource.druid.min-idle=1
spring.datasource.druid.max-active=20
spring.datasource.druid.test-on-borrow=true
spring.datasource.druid.stat-view-servlet.allow=true

####################################################
#
#	mybatis配置
#
####################################################
mybatis.type-aliases-package=com.gzb.SpringBootDemo.po
mybatis.mapper-location=classpath:mapper/*.xml

## 通用mapper设置
mapper.mappers=com.gzb.SpringBootDemo.utils.MyMapper
mapper.not-empty=false
mapper.identity=MYSQL

## 分页插件
pagehelper.helperDialect=mysql
pagehelper.reasonable=true
pagehelper.supportMethodsArguments=true
pagehelper.params=count=countSql

